name: tsdtech_sdk_example
description: Exemplo oficial de uso do TSDTech SDK.
publish_to: 'none'
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Puxa o seu pacote da pasta imediatamente anterior
  tsdtech_client_sdk:
    path: ../

flutter:
  uses-material-design: true