name: tsdtech_client_sdk

description: SDK Dart para integração com a plataforma TsdTech de pagamentos.

repository: https://github.com/tsdtech/tsdtech-client-sdk
homepage: https://github.com/tsdtech/tsdtech-client-sdk
issue_tracker: https://github.com/tsdtech/tsdtech-client-sdk/issues

topics:
  - payment
  - sdk
  - tsdtech

version: 0.2.6

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Networking
  dio: ^5.3.3

  # Dependency injection
  get_it: ^9.2.1

  # State management
  mobx: ^2.3.0
  flutter_mobx: ^2.3.0

  # Local storage
  shared_preferences: ^2.5.3

  # Navigation
  auto_route: ^10.3.0

  # Serialization
  json_annotation: ^4.9.0

  # Internationalization
  intl: ^0.20.2

  # Crypto / payment security
  encrypt: ^5.0.3
  pointycastle: ^3.9.1

  # UI
  qr_flutter: ^4.1.0

  # Utilities
  meta: ^1.12.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  mobx_codegen: ^2.7.0
  json_serializable: ^6.9.0
  # test: ^1.25.0
  mockito: ^5.4.5
  coverage: ^1.11.1
  auto_route_generator: ^10.3.1
  test: ^1.29.0

false_secrets:
  - /test/src/crypto/card_encryptor_test.dart

flutter:
  uses-material-design: true

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/Open Sans Light.ttf
          weight: 300

        - asset: assets/Open Sans Regular.ttf
          weight: 400

        - asset: assets/Open Sans Semibold.ttf
          weight: 600

        - asset: assets/Open Sans Bold.ttf
          weight: 700

  assets:
    - assets/
