name: tsdtech_client_sdk
description: SDK Dart para integração com a plataforma TsdTech de pagamentos.
publish_to: 'none'
repository: https://github.com/tsdtech/tsdtech-client-sdk
homepage: https://github.com/tsdtech/tsdtech-client-sdk
issue_tracker: https://github.com/tsdtech/tsdtech-client-sdk/issues
topics:
  - payment
  - sdk
  - tsdtech

version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.3.3
  http: ^1.4.0
  json_annotation: ^4.9.0
  universal_io: ^2.2.2
  path: ^1.9.1
  platform: ^3.1.5
  meta: ^1.12.0
  intl: ^0.20.2

dev_dependencies:
  test: ^1.25.0
  mockito: ^5.4.0
  coverage: ^1.1.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.0
